### ISSUE TITLE
Can't add invoice/tickets Attachments

### ISSUE THREAD

**Issue by nifunifatralara** [quipuapp/quipu-api-php#3]
Edit: This issue was about the Quipu API not having the ability to add attachments to invoices/tickets thus forcing us to manually upload them. I just found out that this was implemented in the API. It would be awesome if you guys could add it to the PHP library. Thanks!

**Comment by albertbellonch** [comment]
Hi @nifunifatralara,

We're glad that you found this addition to the API useful.

Regarding the possibility of adding it to the PHP library, [as we mentioned in issue #1](https://github.com/quipuapp/quipu-api-php/issues/1#issuecomment-272185207), we want to improve it in the future but still do not have specific plans. We'll have your request into account.

Best,
