### ISSUE TITLE
Composer Integration

### ISSUE THREAD

**Issue by Tilotiti** [quipuapp/quipu-api-php#4]
Hi, is it possible to implement a Composer Integration ? To provide support for Symfony Frameworks and others, like : 

`$ composer require quipuapp/quipi-api-php`

Thank you

**Comment by albertbellonch** [comment]
Hi @Tilotiti,

Thanks for contacting us.

We took a look at it and it makes a lot of sense, so you can already find it published [here](https://packagist.org/packages/quipu/quipu-api). I hope you enjoy it!

Best,
